bigdatagenomics/bdg-formats

scripts/publish-artifacts.sh
* set the bash script to exit 1 if any command fails
* fixed the avro version to 1.7.7
* fixed the git clone command
=> fix artifact/schema publishing

src/main/resources/avro/bdg.avdl
=> [bdg-formats-45] Removing pileup type.

src/main/resources/avro/bdg.avdl
=> [FORMATS-58] Remove flat genotype.

src/main/resources/avro/bdg.avdl
Resolves #62, #65. Based off of feedback from https://github.com/bigdatagenomics/adam/pull/815.
=> Clean up fragment

pom.xml, scripts/publish-artifacts.sh
=> Increase Avro dependency version to 1.8.0

src/main/resources/avro/bdg.avdl
=> add fragmentEndPosition to NucleotideContigFragment

pom.xml
=> Update maven-javadoc-plugin configuration to not fail build on JDK8

src/main/resources/avro/bdg.avdl
=> Fix transcript effect protein length field

README.md
=> [BDG-FORMATS-20] Add readme

src/main/resources/avro/bdg.avdl
Resolves #98. After reverting back, I get:
```
bdg-formats fnothaft$ git diff bdg-formats-0.9.0 --stat
README.md | 40 ++++++++++++++++++++++++++++++++++++++++
pom.xml   |  2 +-
2 files changed, 41 insertions(+), 1 deletion(-)
bdg-formats fnothaft$
```
=> Revert back to 0.9.0

src/main/resources/avro/bdg.avdl
Per comment here https://github.com/bigdatagenomics/bdg-formats/pull/109#issuecomment-258409758
=> Add variant filters for VCF column 7 FILTER

src/main/resources/avro/bdg.avdl
`VariantAnnotation` record doc fixes extracted from #108.
=> Improve doc for VariantAnnotation

src/main/resources/avro/bdg.avdl
=> [FORMATS-112] Harmonize filter representation between Variant and VariantCallingAnnotations

src/main/resources/avro/bdg.avdl
Fixes #118.  Alternate implementation, compare with #119.
=> Use separate fields for Number=R VCF INFO attributes

src/main/resources/avro/bdg.avdl
Fixes #122 
Work towards https://github.com/bigdatagenomics/adam/issues/1219.
=> Add attributes map field to Sequence, Slice, Read records

pom.xml, src/main/resources/avro/bdg.avdl
=> Fix case for default Strand

src/main/resources/avro/bdg.avdl
=> [FORMATS-115] Remove AlignmentRecord.mateAlignmentEnd

src/main/resources/avro/bdg.avdl
=> [FORMATS-146] Add variant quality field.

src/main/resources/avro/bdg.avdl
=> [FORMATS-149] Add splitFromMultiallelic to Variant.

README.md
=> [FORMATS-160] Adding API documentation link and badge.

pom.xml
=> [FORMATS-165] Support JDKs 9 and above.

src/main/resources/avro/bdg.avdl
=> [FORMATS-159] Clean up fields and doc in fragment.

src/main/resources/avro/bdg.avdl
=> [FORMATS-173] Remove quality score variant

pom.xml
=> [FORMATS-179] Use additionalJOptions element instead of additionalparam.

pom.xml
=> [FORMATS-184] Snapshot version should be 0.14.0-SNAPSHOT

src/main/resources/avro/bdg.avdl
=> [FORMATS-181] Use qualityScores for base quality scores

src/main/resources/avro/bdg.avdl
=> [FORMATS-164] Rename AlignmentRecord to Alignment.

.travis.yml, README.md
=> [FORMATS-194] Enable Travis for CI build

CHANGES.md
=> [FORMATS-196] Update changelog for versions 0.14.0 and 0.15.0

src/main/resources/avro/bdg.avdl
=> [FORMATS-202] Add impact, strand, ref/alt coding sequence, ref/alt protein sequence to TranscriptEffect

src/main/resources/avro/bdg.avdl
=> [FORMATS-205] Add sample to Sequence, Slice, and Read

src/main/resources/avro/bdg.avdl
=> [FORMATS-208] Add proteinId field to Feature

pom.xml
=> Update Avro dependency version to 1.11.1
