bigdatagenomics/bdg-formats

pom.xml

This patch is in response to issue #47 I've created.
This code uses the UmlGraphDoc maven plugin to automatically insert UML diagrams from the Java sources (which were generated from the avro files). The `Builder` classes are intentionnally ignored to avoid duplication.
**GraphViz** (dot) is required in the classpath of the target system in order to reap the benefits from this patch.
However, this patch should be **unobtrusive** since it is implemented as a **maven profile**.
```
mvn javadoc:javadoc
mvn javadoc:javadoc -P uml-diagrams
```
Check here for the [class diagram](http://genomic.davidlauzon.net/adam/bdg-formats/org/bdgenomics/formats/avro/org.bdgenomics.formats.avro.png), and [here](http://genomic.davidlauzon.net/adam/bdg-formats/) for the javadoc.
Please verify that this does …

Generate UML diagrams from source (issue #47)

---

src/main/resources/avro/bdg.avdl

Cleans up and adds documentation to the `VariantCallingAnnotation` class. Also makes a bit of cleanup to `Variant` and `Genotype`. Specifically:
* Promote variant quality to the `Variant` object, instead of the `VariantCallingAnnotation` object
* Convert all Phred scaled fields from `int` to `float`
* Pruned a few fields; these were GATK fields that are underdocumented and possibly deprecated (e.g., haplotypeScore). These can still be stored in the tag map.

Clean up VariantCallingAnnotations

---

src/main/resources/avro/bdg.avdl

Flattens entire Variant record into Genotype. Doing so will improve query speed when looking at regions by avoiding nested schemas in Parquet. 
Important things to note:
- This impacts any schemas that previously nested Variant. Right now this is just DatabaseVariantAnnotation, but will impact any other VariantAnnotation schemas, such as those sitting in  #67.

Flatten Variant into Genotype

---

src/main/resources/avro/bdg.avdl

Proposal for variant annotations in VCF as produced by such tools as [SnpEff](http://snpeff.sourceforge.net/) and Ensembl [Variant Effect Predictor (VEP)](http://www.ensembl.org/info/docs/tools/vep/index.html).
VCF annotation ```ANN``` field doc
http://snpeff.sourceforge.net/VCFannotationformat_v1.0.pdf
Annotation branch at GA4GH schemas
https://github.com/ga4gh/schemas/blob/variation_annotation/src/main/resources/avro/alleleAnnotations.avdl
I will add field-level documentation after changes settle down.

Adding schema for variant annotations

---

src/main/resources/avro/bdg.avdl

Maximally disruptive proposal for refactoring feature and related records to support GFF3.
If desirable, I could also propose a minimally disruptive refactoring, but where's the fun in that?
I included a `Contig` &rarr; `contigName` change as elsewhere.

Update feature and related records to support GFF3

---

src/main/resources/avro/bdg.avdl

See https://github.com/bigdatagenomics/adam/issues/1039

Add schema for sample

---

src/main/resources/avro/bdg.avdl

Use separate filtersFailed and filtersPassed arrays for variant quality filters

---

src/main/resources/avro/bdg.avdl

Fixes #89 
Also includes style fixes, removes used Base enum, and removes unused sample fields.

Refactor variant and genotype annotations

---

src/main/resources/avro/bdg.avdl

Fixes #96.
Still needs work; additional changes to come based on VCF mapping review.

Complete refactoring of variant and related annotation records

---

src/main/resources/avro/bdg.avdl

Fixes #100 
Binary incompatible code changes are described by the clirr plugin:
```bash
$ mvn clirr:check
...
[INFO] --- clirr-maven-plugin:2.6.1:check (default-cli) @ bdg-formats ---
[INFO] Comparing to version: 0.9.0
[ERROR] 8001: o.b.f.avro.Base: Class org.bdgenomics.formats.avro.Base removed
[ERROR] 6001: o.b.f.avro.Feature: Removed field isCircular
[ERROR] 7002: o.b.f.avro.Feature: Method 'public java.lang.Boolean getIsCircular()' has been removed
[ERROR] 7002: o.b.f.avro.Feature: Method 'public void setIsCircular(java.lang.Boolean)' has been removed
[ERROR] 7002: o.b.f.avro.Feature$Builder: Method 'public org.bdgenomics.formats.avro.Feature$Builder clearIsCircular()' has been removed
[ERROR] 7002: o.b.f.avro.Feature$Builder: Method 'public java.lang.Boolean getIsCircular()' has been …
```

Code style and doc fixes

---

src/main/resources/avro/bdg.avdl

Fixes #102 
Binary incompatible code changes since 0.9.0:
```bash
$ mvn clirr:check
...
[INFO] --- clirr-maven-plugin:2.6.1:check (default-cli) @ bdg-formats ---
[INFO] Comparing to version: 0.9.0
[ERROR] 8001: o.b.f.avro.Base: Class o.b.f.avro.Base removed
[ERROR] 6001: o.b.f.avro.Feature: Removed field isCircular
[ERROR] 7002: o.b.f.avro.Feature: Method 'public java.lang.Boolean getIsCircular()' has been removed
[ERROR] 7002: o.b.f.avro.Feature: Method 'public void setIsCircular(java.lang.Boolean)' has been removed
[ERROR] 7002: o.b.f.avro.Feature$Builder: Method 'public o.b.f.avro.Feature$Builder clearIsCircular()' has been removed
[ERROR] 7002: o.b.f.avro.Feature$Builder: Method 'public java.lang.Boolean getIsCircular()' has been removed
[ERROR] 7002: o.b.f.avro.Feature$Builder: …
```

Remove StructuralVariant and StructuralVariantType, add names field to Variant

---

src/main/resources/avro/bdg.avdl

* Merge `VariantAnnotation` and `DatabaseVariantAnnotation` records into `VariantAnnotation`
* Align record fields more closely with VCF INFO reserved keys from VCF v4.3 specification
* Document where fields are shared across all alleles in the same VCF record or split for multi-allelic sites
* Document issue with flags for multi-allelic sites in VCF specification, i.e. flags are currently defined as Number=0, whereas they should be Number=A or Number=R
For review:
Draft documentation for mapping is here
https://github.com/heuermh/bdg-formats/blob/docs/docs/source/variants.md
```
$ mvn clirr:check
...
[INFO] --- clirr-maven-plugin:2.6.1:check (default-cli) @ bdg-formats ---
[INFO] Comparing to version: 0.9.0
[ERROR] 8001: org.bdgenomics.formats.avro.Base: Class …
```

Merge VariantAnnotation and DatabaseVariantAnnotation records

---

src/main/resources/avro/bdg.avdl

Add sequence, slice, and read schema.
@akmorrow13:
Please let me know if you think these might be easier to work with than `NucleotideContigFragment`.

Add sequence, slice, and read schema

---

src/main/resources/avro/bdg.avdl

Fixes #116 
Moved `somatic` field from `Variant` to `VariantAnnotation` so that VCF INFO header parsing isn't split between both record types.
Prepares for flattening `VariantAnnotation` into `Variant` at a later date.
Pushed as separate commits since the minor change required reordering the record declarations.

Add forward reference between Variant and VariantAnnotation

---

src/main/resources/avro/bdg.avdl

[FORMATS-127] Use contigName instead of contig

---

src/main/resources/avro/bdg.avdl

[FORMATS-114] Add processing description record.

---

src/main/resources/avro/bdg.avdl

Resolves #138. Makes NucleotideContigFragment start and end fields consistent
with all other record types that map to a single genomic range.

[FORMATS-138] Rename NucleotideContigFragment start/end fields.

---

src/main/resources/avro/bdg.avdl

[FORMATS-144] Move genotype likelihood fields to doubles.

---

src/main/resources/avro/bdg.avdl

[FORMATS-43] Rename contig to reference.

---

src/main/resources/avro/bdg.avdl

`Reference.assembly` field was mistakenly removed in pull request #154 .

Re-add reference.assembly field.

---

src/main/resources/avro/bdg.avdl

Fixes #126, #130, #155 
Cherry-picks commit 060015e481dbbeee7a7d123217ba7c4656f0578e from pull request #143 and then continues to refactor AlignmentRecord, RecordGroup, and ProcessingStep to more closely align with the SAM specification.
Specifically,
RecordGroup &rarr; ReadGroup
RecordGroup.name &rarr; ReadGroup.id
added ReadGroup.platformModel
RecordGroup.sample &rarr; ReadGroup.sampleId
AlignmentRecord.oldPosition &rarr; AlignmentRecord.originalStart
AlignmentRecord.mapq &rarr; AlignmentRecord.mappingQuality
AlignmentRecord.qual &rarr; AlignmentRecord.quality
AlignmentRecord.oldCigar &rarr; AlignmentRecord.originalCigar
AlignmentRecord.origQual &rarr; AlignmentRecord.originalQuality
AlignmentRecord.recordGroupName &rarr; AlignmentRecord.readGroupId
AlignmentRecord.recordGroupSample …

Refactor AlignmentRecord, RecordGroup, and ProcessingStep

---

src/main/resources/avro/bdg.avdl

Fixes #142 
Mapped NucleotideContigFragment fields:
```
contigName --> name
contigLength --> totalLength
description --> description
sequence --> sequence
index --> index
start --> start
end --> end
length --> length
fragments --> slices
```
Unmapped NucleotideContigFragment fields:
None
Unmapped Slice fields:
```
alphabet
strand
attributes
```
This will allow refactoring the org.bdgenomics.adam.rdd.contig package in ADAM to org.bdgenomics.adam.rdd.sequence with not much more than class and field renames.

[FORMATS-142] Replace NucleotideContigFragment with Sequence and Slice
